[package]
name = "pcs"
version = "0.1.0"
edition = "2024"

[dependencies]
blstrs = "0.7.1"
bn = "0.4.3"
num-traits = "0.2.19"
group = "0.13.0"
log = "0.4.20"
env_logger = "0.10.0"
bls12_381 = "0.8.0"
regex = "1.10.1"
blst = { version = "0.3.10", default-features = true }
rand = "0.9.0"